name: "kedge"
version: "0.6.0"
usage: "Simple, Concise & Declarative Kubernetes Applications"
description: |-
  This plugin extends Kedge support to Draft.
ignoreFlags: false
useTunnel: false
command: "$DRAFT_PLUGIN_DIR/kedge.sh"

