name: ticker
labels:
  "draft": "frontend"
containers:
- image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  ports:
  - containerPort: 5000
  env:
  - name: REDIS_HOST
    value: redis
services:
- portMappings:
  - 15000:5000
